#!/bin/bash
### BEGIN INIT INFO
# Provides:          sampleservice
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: sampleservice
# Description:       sampleservice
### END INIT INFO

NAME="logyouweb"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/home/logyou/project/logyou/uih-log-collector-management"
APPCONFIG="$APPDIR/env_server.sh"
APPBIN="/home/logyou/project/django/bin/python"
APPARGS="manage.py runserver 0.0.0.0:8001 --insecure"
USER="logyou"
GROUP="logyou"
PATHPID="/var/run/"

PIDFILE=$PATHPID$NAME.pid

LOCKFILE="/var/lock/subsys/$NAME"


# Source function library.
. /etc/init.d/functions

RETVAL=0


start(){
	echo "Starting Service....."
	if [ ! -f "$LOCKFILE" ]; then
	
		echo "$APPCONFIG\n"

		source "$APPDIR/env_server.sh"
		cd $APPDIR
		daemon --user="$USER" --pidfile="$PIDFILE" "nohup $APPBIN  $APPARGS &"
		RETVAL=$?

		[ $RETVAL -eq 0 ] && touch $LOCKFILE
		echo 
	else
		echo "start $NAME already"
	fi
	return $RETVAL

}

stop(){
        echo -n "Shutting Down Service...."
	ps -ef |grep "$APPARGS" |grep -v grep |awk '{print $2}' |xargs kill -9

        RETVAL=$?
#	[ $RETVAL -eq 0 ] && rm -f $LOCKFILE
	rm -f $LOCKFILE
	statusservice
	echo        
        return $RETVAL
}

statusservice(){
	echo -n "Status Show Service....."
	status "$APPBIN"
	ps -ef |grep "$APPARGS" |grep -v grep
	RETVAL=$?
}

case "$1" in 
start)
	start
   ;;
stop)
	stop
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
	statusservice
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
   RETVAL=2
esac

exit $RETVAL
